name: "AI Code Review Action"
description: "Perform code reviews and comment on diffs using OpenAI API."
inputs:
  GITHUB_TOKEN:
    description: "GitHub token to interact with the repository."
    required: true
  OPENAI_API_KEY:
    description: "OpenAI API key for GPT."
    required: true
  OPENAI_API_MODEL:
    description: "OpenAI API model."
    required: false
    default: "gpt-4"
  OPENAI_API_BASE_URL:
    description: "OpenAI API Base Url like https://my-openai.openai.azure.com/."
    required: true
    default: ""
  OPENAI_API_DEPLOYMENT:
    description: "OpenAI Deployment like gpt4o."
    required: true
    default: ""
  OPENAI_API_VERSION:
    description: "OpenAI API Version like 2024-08-01-preview."
    required: true
    default: ""
  exclude:
    description: "Glob patterns to exclude files from the diff analysis"
    required: false
    default: ""
runs:
  using: "node16"
  main: "dist/index.js"
branding:
  icon: "aperture"
  color: "green"
